on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

     
    - name: Set up kubeconfig
      run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_SECRET }}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          # Verify the configuration:
          kubectl config view
          kubectl cluster-info

    - name: Verify kubectl installation
      run: |
        # Check if kubectl is available
        which kubectl || echo "kubectl is not installed on the runner"
        kubectl version --client || echo "Ensure kubectl is correctly configured"

    - name: Debug Kubeconfig
      run: |
          echo "Testing kubeconfig connection..."
          kubectl config current-context || echo "No current context found. Verify kubeconfig."
          kubectl cluster-info || echo "Failed to connect to the cluster."
          kubectl cluster-info || echo "Failed to connect to the Kubernetes cluster"
          kubectl get nodes || echo "Failed to get nodes from the Kubernetes cluster"

    - name: Apply Kubernetes manifests
      run: |
        # Applying manifests to the Kubernetes cluster
        cd kube
        kubectl config view
        kubectl get nodes  # To verify connection
        kubectl apply -f nginxpod.yaml
        kubectl apply -f prometheuspod.yaml 
        kubectl apply -f grafanapod.yaml 