name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up KUBECONFIG environment variable
      run: |
        # Ensure KUBECONFIG is set to the appropriate file
        export KUBECONFIG=/home/ubuntu/kubeconfig  
        echo "KUBECONFIG environment variable is set to: $KUBECONFIG"
              

    - name: Verify kubectl installation
      run: |
        # Check if kubectl is available
        which kubectl || echo "kubectl is not installed on the runner"
        kubectl version --client || echo "Ensure kubectl is correctly configured"

    - name: Apply Kubernetes manifests
      run: |
        # Applying manifests to the Kubernetes cluster
        cd kube
        export KUBECONFIG=/home/ubuntu/kubeconfig  
        kubectl config view
        kubectl get nodes  # To verify connection
        kubectl apply -f nginxpod.yaml
        kubectl apply -f prometheuspod.yaml 
        kubectl apply -f grafanapod.yaml 
    
    - name: Port-forward Nginx service
      run: |
       # Forward Nginx service's port to access locally on port 8081
         kubectl port-forward svc/nginx-service 8081:80 --namespace=default &
         echo "Port-forwarding Nginx service on http://localhost:8081"
  
    - name: Port-forward Prometheus service
      run: |
       # Forward Prometheus service's port to access locally on port 8082
         kubectl port-forward svc/prometheus-service 8082:9090 --namespace=default &
         echo "Port-forwarding Prometheus service on http://localhost:8082"
  
    - name: Port-forward Grafana service
      run: |
       # Forward Grafana service's port to access locally on port 8083
         kubectl port-forward svc/grafana-service 8083:3000 --namespace=default &
         echo "Port-forwarding Grafana service on http://localhost:8083"