
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubeconfig
      run: |
        # Write the kubeconfig from the secret to a file named 'kubeconfig'
        echo "${{ secrets.KUBECONFIG_SECRET }}" > kubeconfig
        # Export the kubeconfig file path to an environment variable
        export KUBECONFIG=$PWD/kubeconfig
        # Verify the kubeconfig content
        kubectl config view
        kubectl cluster-info
    
    - name: Verify kubectl installation
      run: |
        # Check if kubectl is available
        which kubectl || echo "kubectl is not installed on the runner"
        kubectl version --client || echo "Ensure kubectl is correctly configured"

    - name: Apply Kubernetes manifests
      run: |
        # Applying manifests to the Kubernetes cluster
        kubectl config view
        kubectl get nodes  # To verify connection
        kubectl apply -f kube/nginxpod.yaml
        kubectl apply -f kube/prometheuspod.yaml
        kubectl apply -f kube/grafanapod.yaml 